--Creación de usuario y privilegios
CREATE USER ProyectoIISSI IDENTIFIED BY 1234;
GRANT "CONNECT" TO ProyectoIISSI;
GRANT "RESOURCE" TO ProyectoIISSI;

--Borrado de tablas con restricciones
DROP TABLE Alumnos CASCADE CONSTRAINTS;
DROP TABLE AlumnosPertenecenAGrupos CASCADE CONSTRAINTS;
DROP TABLE Asignaturas CASCADE CONSTRAINTS;
DROP TABLE AsignaturasPuntuadasConNotas CASCADE CONSTRAINTS;
DROP TABLE AsignaturasImpartidasEnAulas CASCADE CONSTRAINTS;
DROP TABLE AsignaturasPertenecenAGrados CASCADE CONSTRAINTS;
DROP TABLE Aulas CASCADE CONSTRAINTS;
DROP TABLE Becarios CASCADE CONSTRAINTS;
DROP TABLE Becas CASCADE CONSTRAINTS;
DROP TABLE Departamentos CASCADE CONSTRAINTS;
DROP TABLE Despachos CASCADE CONSTRAINTS;
DROP TABLE Expedientes CASCADE CONSTRAINTS;
DROP TABLE Grados CASCADE CONSTRAINTS;
DROP TABLE Grupos CASCADE CONSTRAINTS;
DROP TABLE GruposAsistenAClaseEnAulas CASCADE CONSTRAINTS;
DROP TABLE Matriculas CASCADE CONSTRAINTS;
DROP TABLE MatriculasContienenAsignaturas CASCADE CONSTRAINTS;
DROP TABLE MatriculasPertenecenAGrados CASCADE CONSTRAINTS;
DROP TABLE Notas CASCADE CONSTRAINTS;
DROP TABLE Profesores CASCADE CONSTRAINTS;
DROP TABLE ProfesoresImpartenAsignaturas CASCADE CONSTRAINTS;
DROP TABLE ProfesoresImpartenEnGrupos CASCADE CONSTRAINTS;
DROP TABLE Tutorias CASCADE CONSTRAINTS;

--Borrado de secuencias
DROP SEQUENCE SEC_Aulas;
DROP SEQUENCE SEC_Departamentos;
DROP SEQUENCE SEC_Despachos;
DROP SEQUENCE SEC_Grados;
DROP SEQUENCE SEC_Grupos;
DROP SEQUENCE SEC_Notas;
DROP SEQUENCE SEC_Tutorias;